# Generated by Django 5.1.4 on 2025-01-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('category', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('runningTime', models.TextField()),
                ('review', models.TextField()),
                ('director', models.TextField()),
                ('actor', models.TextField()),
            ],
        ),
    ]
